"""Added descriptions

Revision ID: e8d14f6eed6c
Revises: 34331327c046
Create Date: 2022-12-30 12:55:14.874739

"""
from alembic import op
import sqlalchemy as sa
from common.database.models import *


# revision identifiers, used by Alembic.
revision = 'e8d14f6eed6c'
down_revision = '34331327c046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('description', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'description')
    # ### end Alembic commands ###
