version: "3.1"

services:
  api:
    restart: "no"
    build:
      context: .
    volumes:
      - ./src:/code/src
      - ./secrets:/run/secrets
    ports:
      - "80:80"
    depends_on:
      - db
    container_name: "tasktracker-api"
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; /root/.local/bin/poetry run uvicorn api.main:api --proxy-headers --host 0.0.0.0 --port 80'
    env_file:
      - ./secrets/db.env
  db:
    restart: unless-stopped
    image: postgres:13-alpine
    env_file:
      - secrets/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./secrets:/run/secrets
    expose:
      - 5432

  db_migrate:
    restart: "no"
    build:
      context: .
    volumes:
      - ./src:/code/src
    depends_on:
      - db
    env_file:
      - ./secrets/db.env
    command: bash -c 'cd /code/src/common/database/alembic; /root/.local/bin/poetry run alembic upgrade head'

  db_create_migration_file:
      restart: "no"
      build:
        context: .
      volumes:
        - ./src:/code/src
      depends_on:
        - db
      env_file:
        - ./secrets/db.env
      command: bash -c 'cd /code/src/common/database/alembic; /root/.local/bin/poetry run alembic revision --autogenerate -m "${REVISION_MESSAGE}"'


volumes:
  postgres_data:

